T_MEAP93<-read.table("C:/Users/klusk/Projects/R-studies/Examples/MEAP93.txt", header= TRUE, sep="")
reg1_MEAP93=lm(math10~enroll+staff+totcomp, data = T_MEAP93)
reg2_MEAP93=lm(math10~log(enroll)+log(staff)+log(totcomp), data = T_MEAP93)
reg3_MEAP93=lm(math10~log(enroll)+log(staff)+log(totcomp)+lnchprg, data = T_MEAP93)
reg4_MEAP93=lm(math10~log(enroll)+log(totcomp)+lnchprg, data = T_MEAP93)
Greg1_MEAP93 <- plot(reg1_MEAP93)
library(car)
library(lmtest)
library(skedastic)
library(sandwich)
confidence_interval <- qqPlot(reg1_MEAP93,distribution="norm")
BGtest_1 <- bgtest(reg1_MEAP93)
BGtest_4 <- bgtest(reg4_MEAP93)
DWtest_1 <- dwtest(reg1_MEAP93)
DWtest_4 <- dwtest(reg4_MEAP93)
White_test_1=white_lm(reg1_MEAP93, interactions=FALSE, statonly=FALSE)
White_test_crossed_1=white_lm(reg1_MEAP93, interactions=TRUE, statonly=FALSE)
White_test_4=white_lm(reg4_MEAP93, interactions=FALSE, statonly=FALSE)
White_test_crossed_4=white_lm(reg4_MEAP93, interactions=TRUE, statonly=FALSE)
T_robust=coeftest(reg4_MEAP93, vcov=vcovHC(reg4_MEAP93, type = 'HC0'))
print(summary(reg1_MEAP93))
print(summary(reg2_MEAP93))
print(summary(reg3_MEAP93))
print(summary(reg4_MEAP93))
print(Greg1_MEAP93)
print(confidence_interval)
print(BGtest_1)
print(BGtest_4)
print(DWtest_1)
print(DWtest_4)
print(White_test_1)
print(White_test_4)
print(White_test_crossed_1)
print(White_test_crossed_4)
print(T_robust)