tabela_9.7<-read.table("C:/Users/klusk/Projects/R-studies/Examples/tabela_9.7.txt", header= TRUE, sep="")
reg1_tabela_9.7=lm(rs~idade+dgen+de2+de3+de4+dpt+dgen*de3+dgen*de4, data = tabela_9.7)
reg2_tabela_9.7=lm(rs~idade+dgen+de4, data = tabela_9.7)
Greg1_tabela_9.7 <- plot(reg1_tabela_9.7)
library(car)
library(lmtest)
library(skedastic)
library(sandwich)
confidence_interval <- qqPlot(reg1_tabela_9.7,distribution="norm")
BGtest_2_1 <- bgtest(reg1_tabela_9.7)
BGtest_2_3 <- bgtest(reg2_tabela_9.7)
DWtest_2_1 <- dwtest(reg1_tabela_9.7)
DWtest_2_3 <- dwtest(reg2_tabela_9.7)
White_test_1=white_lm(reg1_tabela_9.7, interactions=FALSE, statonly=FALSE)
White_test_crossed_1=white_lm(reg1_tabela_9.7, interactions=TRUE, statonly=FALSE)
White_test_2=white_lm(reg2_tabela_9.7, interactions=FALSE, statonly=FALSE)
White_test_crossed_2=white_lm(reg2_tabela_9.7, interactions=TRUE, statonly=FALSE)
T_robust=coeftest(reg2_tabela_9.7, vcov=vcovHC(reg2_tabela_9.7, type = 'HC0'))
print(summary(reg1_tabela_9.7))
print(summary(reg2_tabela_9.7))
print(Greg1_tabela_9.7)
print(confidence_interval)
print(BGtest_2_1)
print(BGtest_2_3)
print(DWtest_2_1)
print(DWtest_2_3)
print(White_test_1)
print(White_test_2)
print(White_test_crossed_1)
print(White_test_crossed_2)
print(T_robust)